const staticRoleMap: Record<string, string> = {
    'backend engineer': 'Owns core APIs, business logic, and data modeling. Ensures reliability, performance, and testability.',
    'cloud engineer': 'Optimizes cloud resource allocation, implements cost-saving strategies, and ensures high availability of cloud services.',
    'cloud security engineer': 'Designs and implements security controls for cloud environments, protecting data and systems from threats.',
    'data analyst': 'Analyzes data to inform business decisions, using tools like SQL, Python, and BI platforms.',
    'data architect': 'Designs data storage systems, ensuring scalability, security, and efficient data access patterns.',
    'data engineer': 'Design robust ETL pipelines and optimize data quality across systems.',
    'data product manager': 'Owns data-centric products, aligning data capabilities with business needs. Translates model outcomes into product decisions.',
    'data scientist': 'Applies statistical and ML techniques to extract insights from data, often using Python and cloud tools.',
    'data visualization engineer': 'Creates interactive, data-driven visualizations using libraries like D3.js or Tableau.',
    'devops engineer': 'Streamlines CI/CD pipelines, automates deployments, and ensures consistent environments across teams.',
    'devops security engineer': 'Automates security checks, monitors compliance, and ensures secure operations across development and production environments.',
    'devsecops engineer': 'Integrates security practices into development workflows, ensuring secure code and infrastructure.',
    'engineering manager': 'Oversees technical execution, team productivity, and alignment with company goals. Balances people management with system design guidance.',
    'frontend engineer': 'Focus on performance, accessibility, and intuitive UI flows.',
    'fullstack engineer': 'Builds both frontend and backend features, owning the full delivery cycle across the stack.',
    'fullstack tech lead': 'Owns end-to-end delivery across frontend and backend systems. Balances short-term features with long-term code health.',
    'generative ai engineer': 'Focuses on building and integrating LLM-powered features, fine-tuning models, and prompt chaining workflows.',
    'infrastructure engineer': 'Automates infra provisioning, monitors systems health, and enables scalability under load.',
    'machine learning engineer': 'Emphasize model accuracy, data versioning, and scalable inference.',
    'mlops engineer': 'Builds CI/CD pipelines for ML models, manages inference infra, and ensures reproducibility of model outputs.',
    'mobile engineer': 'Develops performant, intuitive mobile apps using native or cross-platform tools. Prioritizes UX, offline handling, and efficient APIs.',
    'observability engineer': 'Builds tooling and practices for visibility across services—logs, traces, metrics, and alerts.',
    'platform engineer': 'Consider infrastructure abstraction, CI/CD, and developer experience.',
    'platform tech lead': 'Guides infrastructure design for developer experience, CI/CD systems, and shared tooling.',
    'principal engineer': 'Shapes engineering vision, scales systems org-wide, and aligns technical initiatives with business outcomes.',
    'privacy engineer': 'Implements compliance requirements (GDPR, HIPAA, etc.) into systems architecture, balancing utility with regulatory needs.',
    'product manager': 'Include tradeoffs between business goals, user needs, and technical feasibility.',
    'product-minded engineer': 'Deeply collaborates with design and PM. Prioritizes user outcomes while building maintainable systems.',
    'prompt engineer': 'Designs, tests, and iterates on prompts for LLMs. Balances creativity with reliability and traceability.',
    'quality assurance engineer': 'Defines testing strategy, automates regression coverage, and ensures release confidence.',
    'research engineer': 'Bridges ML research and implementation, rapidly prototyping novel architectures and validating results at scale.',
    'security engineer': 'Evaluate threat models, secure architecture, and compliance constraints.',
    'site reliability engineer': 'Focus on scalability, fault tolerance, and latency under real-time load.',
    'software engineer': 'Implements reliable, maintainable systems that balance business needs, user experience, and technical tradeoffs.',
    'solutions architect': 'Designs client-specific architectures, often across multiple services or systems. Balances scalability, cost, and maintainability.',
    'staff engineer': 'Drives cross-team architecture decisions, mentors other engineers, and owns long-term technical strategy.',
    'tech lead': 'Responsible for architectural direction, mentoring team members, and ensuring delivery alignment across stakeholders.',
    'technical product manager': 'Translates technical constraints into product opportunities. Collaborates closely with engineering to align feasibility and impact.',
    'ux engineer': 'Bridges design and code. Implements highly interactive, accessible, and pixel-perfect user interfaces.',
    'vector database engineer': 'Designs and optimizes vector-based search systems for embeddings, with emphasis on recall precision and latency.',
};

export default staticRoleMap; 