import { Repository } from '../../molecules/RepoCard/RepoCard.types';

export const mockRepositories: Repository[] = [
  {
    id: '1',
    name: 'react-component-library',
    description: 'A comprehensive React component library built with TypeScript and styled-components. Includes buttons, forms, cards, modals, and more.',
    url: 'https://github.com/username/react-component-library',
    language: 'TypeScript',
    stars: 245,
    forks: 45,
    issues: 12,
    lastUpdated: '2023-06-15T10:00:00Z',
    isPrivate: false,
    topics: ['react', 'typescript', 'ui', 'component-library', 'frontend'],
  },
  {
    id: '2',
    name: 'next-auth-starter',
    description: 'A starter template for Next.js applications with authentication already set up. Uses Next-Auth for authentication with various providers.',
    url: 'https://github.com/username/next-auth-starter',
    language: 'TypeScript',
    stars: 178,
    forks: 32,
    issues: 5,
    lastUpdated: '2023-07-22T14:30:00Z',
    isPrivate: false,
    topics: ['nextjs', 'auth', 'typescript', 'template'],
  },
  {
    id: '3',
    name: 'data-visualization-dashboard',
    description: 'An interactive dashboard for data visualization using D3.js and React. Features customizable charts, filters, and real-time updates.',
    url: 'https://github.com/username/data-visualization-dashboard',
    language: 'JavaScript',
    stars: 302,
    forks: 67,
    issues: 21,
    lastUpdated: '2023-05-08T09:15:00Z',
    isPrivate: false,
    topics: ['d3', 'react', 'data-visualization', 'dashboard', 'javascript'],
  },
  {
    id: '4',
    name: 'serverless-api',
    description: 'A serverless API built with AWS Lambda and API Gateway. Includes authentication, database integration, and comprehensive documentation.',
    url: 'https://github.com/username/serverless-api',
    language: 'JavaScript',
    stars: 124,
    forks: 28,
    issues: 7,
    lastUpdated: '2023-04-30T11:45:00Z',
    isPrivate: false,
    topics: ['serverless', 'aws', 'lambda', 'api', 'backend'],
  },
  {
    id: '5',
    name: 'python-ml-toolkit',
    description: 'A collection of tools and utilities for machine learning projects in Python. Includes data preprocessing, model training, and visualization.',
    url: 'https://github.com/username/python-ml-toolkit',
    language: 'Python',
    stars: 387,
    forks: 92,
    issues: 16,
    lastUpdated: '2023-03-12T16:20:00Z',
    isPrivate: false,
    topics: ['python', 'machine-learning', 'data-science', 'toolkit'],
  },
  {
    id: '6',
    name: 'go-microservices',
    description: 'A template for building microservices architecture with Go. Includes service discovery, API gateway, and message queues.',
    url: 'https://github.com/username/go-microservices',
    language: 'Go',
    stars: 156,
    forks: 41,
    issues: 8,
    lastUpdated: '2023-08-05T08:30:00Z',
    isPrivate: false,
    topics: ['go', 'microservices', 'docker', 'kubernetes', 'backend'],
  },
]; 