import { AudioTrack } from '../DualAudio.types';

// Generated by pnpm content:pipeline audio:tracks. Do not edit by hand.
export const generatedBlogVoiceTracks: AudioTrack[] = [
  {
    "id": "academic-research-is-a-software-patch-and-i-finally-have-a-way-to-install-it",
    "title": "Academic Research Is a Software Patch (And I Finally Have a Way to Install It)",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/academic-research-is-a-software-patch-and-i-finally-have-a-way-to-install-it.mp3",
    "description": "Audio version of Academic Research Is a Software Patch (And I Finally Have a Way to Install It)."
  },
  {
    "id": "alphabetize-your-code",
    "title": "Alphabetize your code.",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/alphabetize-your-code.mp3",
    "description": "Audio version of Alphabetize your code.."
  },
  {
    "id": "building-with-brain-garden-real-world-lessons-in-practical-ai",
    "title": "Building with Brain Garden: Real-World Lessons in Practical AI",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/building-with-brain-garden-real-world-lessons-in-practical-ai.mp3",
    "description": "Audio version of Building with Brain Garden: Real-World Lessons in Practical AI."
  },
  {
    "id": "developing-with-a-team-of-ai-s",
    "title": "Developing with a Team of AI’s",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/developing-with-a-team-of-ai-s.mp3",
    "description": "Audio version of Developing with a Team of AI’s."
  },
  {
    "id": "every-company-is-sitting-on-sunken-treasure",
    "title": "Every Company Is Sitting on Sunken Treasure",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/every-company-is-sitting-on-sunken-treasure.mp3",
    "description": "Audio version of Every Company Is Sitting on Sunken Treasure."
  },
  {
    "id": "factory-amplification-and-modular-primitives",
    "title": "Factory Amplification and Modular Primitives",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/factory-amplification-and-modular-primitives.mp3",
    "description": "Audio version of Factory Amplification and Modular Primitives."
  },
  {
    "id": "how-to-make-your-ai-code-look-human",
    "title": "How to Make Your AI Code Look Human",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/how-to-make-your-ai-code-look-human.mp3",
    "description": "Audio version of How to Make Your AI Code Look Human."
  },
  {
    "id": "judgment-over-keystrokes",
    "title": "Judgment Over Keystrokes",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/judgment-over-keystrokes.mp3",
    "description": "Audio version of Judgment Over Keystrokes."
  },
  {
    "id": "pixel-precision-in-developer-tools-what-i-learned-building-designer-cloud",
    "title": "Pixel Precision in Developer Tools: What I Learned Building Designer Cloud",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/pixel-precision-in-developer-tools-what-i-learned-building-designer-cloud.mp3",
    "description": "Audio version of Pixel Precision in Developer Tools: What I Learned Building Designer Cloud."
  },
  {
    "id": "reality-needs-observers",
    "title": "Reality Needs Observers",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/reality-needs-observers.mp3",
    "description": "Audio version of Reality Needs Observers."
  },
  {
    "id": "reuse-your-code-authoring-your-own-universal-library-with-webpack",
    "title": "Reuse your code: Authoring your own Universal Library with Webpack",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/reuse-your-code-authoring-your-own-universal-library-with-webpack.mp3",
    "description": "Audio version of Reuse your code: Authoring your own Universal Library with Webpack."
  },
  {
    "id": "the-ai-cost-rug-pull-isnt-a-bubble-its-a-filter",
    "title": "The AI Cost Rug Pull Isn't a Bubble. It's a Filter.",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-ai-cost-rug-pull-isnt-a-bubble-its-a-filter.mp3",
    "description": "Audio version of The AI Cost Rug Pull Isn't a Bubble. It's a Filter.."
  },
  {
    "id": "the-beauty-of-es6s-object-destructuring-assignment",
    "title": "The Beauty of ES6's Object Destructuring Assignment",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-beauty-of-es6s-object-destructuring-assignment.mp3",
    "description": "Audio version of The Beauty of ES6's Object Destructuring Assignment."
  },
  {
    "id": "the-factory",
    "title": "The Factory",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-factory.mp3",
    "description": "Audio version of The Factory."
  },
  {
    "id": "the-foreman",
    "title": "The Foreman",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-foreman.mp3",
    "description": "Audio version of The Foreman."
  },
  {
    "id": "the-golden-hammer",
    "title": "The Golden Hammer",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-golden-hammer.mp3",
    "description": "Audio version of The Golden Hammer."
  },
  {
    "id": "the-moving-target",
    "title": "The Moving Target",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-moving-target.mp3",
    "description": "Audio version of The Moving Target."
  },
  {
    "id": "the-overnight-shift",
    "title": "The Overnight Shift",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/the-overnight-shift.mp3",
    "description": "Audio version of The Overnight Shift."
  },
  {
    "id": "what-i-learned-building-a-photoshop-in-the-browser",
    "title": "What I Learned Building a Photoshop in the Browser",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/what-i-learned-building-a-photoshop-in-the-browser.mp3",
    "description": "Audio version of What I Learned Building a Photoshop in the Browser."
  },
  {
    "id": "why-character-choice-matters-in-agent-design",
    "title": "Why Character Choice Matters in Agent Design",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/why-character-choice-matters-in-agent-design.mp3",
    "description": "Audio version of Why Character Choice Matters in Agent Design."
  },
  {
    "id": "why-you-should-encapsulate-your-javascript-conditionals-in-a-function",
    "title": "Why you should Encapsulate your Javascript Conditionals in a Function",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/why-you-should-encapsulate-your-javascript-conditionals-in-a-function.mp3",
    "description": "Audio version of Why you should Encapsulate your Javascript Conditionals in a Function."
  },
  {
    "id": "your-ai-isnt-hallucinating-its-lying",
    "title": "Your AI Isn't Hallucinating. It's Lying.",
    "artist": "Narration by David Mieloch",
    "src": "/audio/voice/blog/your-ai-isnt-hallucinating-its-lying.mp3",
    "description": "Audio version of Your AI Isn't Hallucinating. It's Lying.."
  }
];
